"""empty message

Revision ID: 232e07928edb
Revises: 626d170dd6fa
Create Date: 2024-12-05 12:10:41.354539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232e07928edb'
down_revision = '626d170dd6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_data')
    # ### end Alembic commands ###
